# Generated by Django 6.0.7 on 2026-07-17 17:43

import patient.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[patient.validators.validate_date_of_birth]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(max_length=100, validators=[patient.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_number',
            field=models.CharField(max_length=10, validators=[patient.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, validators=[patient.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100, validators=[patient.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[patient.validators.validate_phone]),
        ),
    ]
