# Generated by Django 6.0.7 on 2026-07-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_photo_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_name',
        ),
    ]
