# Generated by Django 6.0.7 on 2026-07-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patient_emergency_contact_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('view_patient_details', 'Can view patient details'), ('edit_patient_details', 'Can edit patient details'), ('delete_patient_details', 'Can delete patient details')]},
        ),
    ]
