# Generated by Django 6.0.7 on 2026-07-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_medicalrecord_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
