# Generated by Django 6.0.7 on 2026-07-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_medicalrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_number',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
