# Generated by Django 6.0.7 on 2026-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_billing_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
