# Generated by Django 6.0.7 on 2026-08-05 14:30

import django.db.models.deletion
import patient.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['-bill_date'], 'permissions': [('view_bill', 'Can view bills'), ('edit_bill', 'Can edit bills'), ('download_bill', 'Can download bills')]},
        ),
        migrations.AlterModelOptions(
            name='insuranceclaim',
            options={'ordering': ['-created_at'], 'permissions': [('verify_claim', 'Can verify insurance claim'), ('approve_claim', 'Can approve insurance claim'), ('reject_claim', 'Can reject insurance claim')]},
        ),
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'ordering': ['company_name'], 'permissions': [('view_company', 'Can view insurance company'), ('edit_company', 'Can edit insurance company'), ('verify_claim', 'Can verify insurance claim'), ('approve_claim', 'Can approve insurance claim'), ('reject_claim', 'Can reject insurance claim')]},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-visit_date'], 'permissions': [('view_medical_record', 'Can view medical records'), ('edit_medical_record', 'Can edit medical records'), ('delete_medical_record', 'Can delete medical records')]},
        ),
        migrations.AddField(
            model_name='billing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[patient.validators.validate_phone]),
        ),
    ]
