# Generated by Django 6.0.7 on 2026-08-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_medicalrecord_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='photo',
            new_name='profile_photo',
        ),
    ]
