# Generated by Django 6.0.7 on 2026-08-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_rename_photo_patient_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_number',
        ),
    ]
